### ISSUE TITLE
Elevator Use

### ISSUE THREAD

**Issue by RedRowBoat** [JDDev0/WorldMaster#1]
I can't seem to figure out how to use the elevator once it's been created. I'm running on version 1.0.8

Sorry if you've been asked this a million times, I tried to find an FAQ and couldn't

**Comment by JDDev0** [comment]
Firstly you need to add floors to your elevator by placing an iron door and then registering the floor with /elevator add_floor \<NAME\> \<FLOOR\> \<DoorX\> \<DoorY\> \<DoorZ\> (NAME is the elevator name the floor is added to; FLOOR is the name of the floor (e.g. Floor0, spaces are not allowed); DoorX Y and Z will be shown as an autocompletion if you face the door).

![2022-07-26_18 35 46](https://user-images.githubusercontent.com/37939362/181061779-e8bd8301-a5d0-485d-aa32-1df3e342096e.png)
![2022-07-26_18 36 55](https://user-images.githubusercontent.com/37939362/181061957-327ceb56-eba2-4d17-be4d-a7beec23e8d2.png)

The speed of the elevator can be increased by using /elevator set_speed \<NAME\> \<Speed in blocks per second\>.

In order to move the elevator you need to be near it and then you need to type /elevator move \<FLOOR\>. (FLOOR is the floor you want the elevator to move to [Works with tab autocompletion])

![2022-07-26_18 37 14](https://user-images.githubusercontent.com/37939362/181062004-c6e1cbc5-79d7-44e1-9644-97090019e76e.png)
![2022-07-26_18 37 27](https://user-images.githubusercontent.com/37939362/181062051-7b2e0d7f-7dfa-4af0-85d7-08a8e089d383.png)
